# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d52c9287a09da6519f41c37e1ae28e1d90771242d32bdd4555402da7b0b57b5a261c6cd967ed8c57588c9686476a92b7a4a0312085c50fe1e2aa12e3156ab5c1

test:
  secret_key_base: f7b5096a85898db8c5974082cc30a29173475aba0199a0e8c694ad1b48580961329784719fe0c5d87a675c841f90c854de9dd3fbe33b37ec6c814501122e6f69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
